version: "2.1"
services:
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - AUTO_UPDATE=true #optional
            # - RUN_OPTS=<run options here> #optional
        volumes:
            - ./jackett/config:/config
            - ./jackett/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./sonarr/config:/config
            - ./sonarr/series:/tv #optional
            # - /path/to/downloadclient-downloads:/downloads #optional
        ports:
            - 8989:8989
        restart: unless-stopped

    transmission:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
            # - USER=username #optional
            # - PASS=password #optional
            # - WHITELIST=iplist #optional
            # - PEERPORT=peerport #optional
            # - HOST_WHITELIST=dnsname list #optional
        volumes:
            - ./transmission/config:/config
            - ./transmission/downloads:/downloads
            - ./transmission/watch:/watch
        ports:
            - 9091:9091
            - 51414:51413
            - 51414:51413/udp
        restart: unless-stopped
